// Segment metadata for Interactive Video
// Auto-generated by SCORM export
// Video ID: 7c8b94b803764f6da9768f5772404164

window.SEGMENT_METADATA = [
  {
    "segmentId": "default",
    "videoId": "7c8b94b803764f6da9768f5772404164",
    "sceneIds": [
      "VTiXDa16",
      "04g5Bldm",
      "n7bJDagL",
      "TPmNzHG8",
      "ikHCSoEp",
      "aAY66RP3",
      "AyXXDiqw",
      "5AxRpdgr",
      "ccbM3Kx2",
      "75JstNna",
      "Y1YHnup7",
      "kLobGczM",
      "nq8UyyKc",
      "lJw4Qw6d",
      "1I78WJ5r",
      "muK7JWKf",
      "yyR13GCd",
      "oxx7VC7s",
      "YTA8hZ1d"
    ],
    "videoUrl": "https://resource2.heygen.ai/aws_pacific/avatar_tmp/6d88f4bf84fa43d5879291f8cc0b673b/vAcSobXVj6G4hLdvdddbsY8UwFpx2RW1C/caption_7c8b94b803764f6da9768f5772404164.mp4"
  }
];
